# Generated by Django 3.1.2 on 2020-10-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201027_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='picture',
            new_name='img',
        ),
    ]
