# Generated by Django 3.1.2 on 2020-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='top',
            field=models.BooleanField(default=True),
        ),
    ]
