# Generated by Django 3.1.2 on 2020-10-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='picture',
            new_name='img',
        ),
    ]
